apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: test
spec:
  version: 8.2.0
  count: 1
  elasticsearchRef:
    name: quickstart
    namespace: test
  http:
    service:
      spec:
        type: NodePort
